/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guias4;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonella
 */
public class registro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(registro.class.getName());
    private UsuarioDAO dao = new UsuarioDAO();
    private DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
    mostrarUsuarios();
    txt_id.setEditable(false);
    this.setLocationRelativeTo(null);
    this.setResizable(false);
    }

    public void mostrarUsuarios() {
    modelo.setRowCount(0);
    modelo.setColumnCount(0);

    modelo.addColumn("ID");
    modelo.addColumn("Cedula");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido");
    modelo.addColumn("Edad");

    List<Usuario> lista = dao.listar();

    for (Usuario u : lista) {
        Object[] fila = {
            u.getId(),
            u.getCedula(),
            u.getNombre(),
            u.getApellido(),
            u.getEdad()
        };
        modelo.addRow(fila);
    }

    tabla.setModel(modelo);
}
    public void limpiarCampos() {
    txt_id.setText("");
    txt_cedula2.setText("");
    txt_nombre2.setText("");
    txt_apellido2.setText("");
    txt_edad2.setText("");
   
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_cedula2 = new javax.swing.JTextField();
        txt_nombre2 = new javax.swing.JTextField();
        txt_edad2 = new javax.swing.JTextField();
        txt_apellido2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_buscar2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        bnt_modificar = new javax.swing.JButton();
        bnt_buscar = new javax.swing.JButton();
        bnt_guardar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btn_eliminar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido");

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("ID");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nombre");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Apellido");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Edad");

        txt_cedula2.addActionListener(this::txt_cedula2ActionPerformed);

        txt_nombre2.addActionListener(this::txt_nombre2ActionPerformed);

        txt_edad2.addActionListener(this::txt_edad2ActionPerformed);

        txt_apellido2.addActionListener(this::txt_apellido2ActionPerformed);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Cedula");

        txt_id.addActionListener(this::txt_idActionPerformed);

        txt_buscar2.addActionListener(this::txt_buscar2ActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_buscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_edad2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cedula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_edad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(txt_buscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        bnt_modificar.setBackground(new java.awt.Color(255, 255, 51));
        bnt_modificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bnt_modificar.setForeground(new java.awt.Color(0, 0, 0));
        bnt_modificar.setText("Modificar");
        bnt_modificar.addActionListener(this::bnt_modificarActionPerformed);

        bnt_buscar.setBackground(new java.awt.Color(204, 204, 204));
        bnt_buscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bnt_buscar.setForeground(new java.awt.Color(0, 0, 0));
        bnt_buscar.setText("Buscar");
        bnt_buscar.addActionListener(this::bnt_buscarActionPerformed);

        bnt_guardar.setBackground(new java.awt.Color(0, 255, 0));
        bnt_guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bnt_guardar.setForeground(new java.awt.Color(0, 0, 0));
        bnt_guardar.setText("Guardar");
        bnt_guardar.addActionListener(this::bnt_guardarActionPerformed);

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("*Clik para selecionar el registro");

        btn_eliminar1.setBackground(new java.awt.Color(204, 0, 51));
        btn_eliminar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_eliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar1.setText("Eliminar");
        btn_eliminar1.addActionListener(this::btn_eliminar1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 455, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bnt_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bnt_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_eliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bnt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bnt_modificar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bnt_guardar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12)
                        .addComponent(btn_eliminar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnt_buscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cedula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedula2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedula2ActionPerformed

    private void txt_nombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre2ActionPerformed

    private void txt_edad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edad2ActionPerformed

    private void txt_apellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellido2ActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar2ActionPerformed

    private void bnt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_modificarActionPerformed

        if (txt_id.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla");
    return;
}

if (txt_cedula2.getText().trim().isEmpty() ||
    txt_nombre2.getText().trim().isEmpty() ||
    txt_apellido2.getText().trim().isEmpty() ||
    txt_edad2.getText().trim().isEmpty()) {
    
    JOptionPane.showMessageDialog(this, "Complete todos los campos");
    return;
}

Usuario u = new Usuario();
u.setId(Integer.parseInt(txt_id.getText()));
u.setCedula(txt_cedula2.getText());
u.setNombre(txt_nombre2.getText());
u.setApellido(txt_apellido2.getText());
u.setEdad(Integer.parseInt(txt_edad2.getText()));

if (dao.modificar(u)) {
    JOptionPane.showMessageDialog(this, "Usuario modificado correctamente");
    limpiarCampos();
    mostrarUsuarios();
} else {
    JOptionPane.showMessageDialog(this, "Error al modificar");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_modificarActionPerformed

    private void bnt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_buscarActionPerformed
        
if (txt_buscar2.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Ingrese una cédula para buscar");
    return;
}

String cedula = txt_buscar2.getText().trim();
Usuario u = dao.buscarPorCedula(cedula);

if (u != null) {
    txt_id.setText(String.valueOf(u.getId()));
    txt_cedula2.setText(u.getCedula());
    txt_nombre2.setText(u.getNombre());
    txt_apellido2.setText(u.getApellido());
    txt_edad2.setText(String.valueOf(u.getEdad()));
} else {
    JOptionPane.showMessageDialog(this, "Usuario no encontrado");
    limpiarCampos();
    txt_buscar2.setText(cedula);
}
// TODO add your handling code here:
    }//GEN-LAST:event_bnt_buscarActionPerformed

    private void bnt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_guardarActionPerformed
       
        if (txt_cedula2.getText().trim().isEmpty() ||
    txt_nombre2.getText().trim().isEmpty() ||
    txt_apellido2.getText().trim().isEmpty() ||
    txt_edad2.getText().trim().isEmpty()) {
    
    JOptionPane.showMessageDialog(this, "Complete todos los campos");
    return;
}

if (!txt_cedula2.getText().matches("\\d+")) {
    JOptionPane.showMessageDialog(this, "La cédula debe ser numérica");
    return;
}

if (!txt_edad2.getText().matches("\\d+")) {
    JOptionPane.showMessageDialog(this, "La edad debe ser numérica");
    return;
}

Usuario u = new Usuario();
u.setCedula(txt_cedula2.getText());
u.setNombre(txt_nombre2.getText());
u.setApellido(txt_apellido2.getText());
u.setEdad(Integer.parseInt(txt_edad2.getText()));

if (dao.guardar(u)) {
    JOptionPane.showMessageDialog(this, "Usuario guardado correctamente");
    limpiarCampos();
    mostrarUsuarios();
} else {
    JOptionPane.showMessageDialog(this, "Error al guardar");
}
    }//GEN-LAST:event_bnt_guardarActionPerformed

    private void btn_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar1ActionPerformed
        if (txt_id.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla");
    return;
}

int id = Integer.parseInt(txt_id.getText());

if (dao.eliminar(id)) {
    JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente");
    limpiarCampos();
    mostrarUsuarios();
} else {
    JOptionPane.showMessageDialog(this, "Error al eliminar");
}        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminar1ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
       
        int fila = tabla.getSelectedRow();
        

txt_id.setText(tabla.getValueAt(fila, 1).toString());
txt_cedula2.setText(tabla.getValueAt(fila, 2).toString());
txt_nombre2.setText(tabla.getValueAt(fila, 3).toString());
txt_apellido2.setText(tabla.getValueAt(fila, 4).toString());
txt_edad2.setText(tabla.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new registro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_buscar;
    private javax.swing.JButton bnt_guardar;
    private javax.swing.JButton bnt_modificar;
    private javax.swing.JButton btn_eliminar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_apellido1;
    private javax.swing.JTextField txt_apellido2;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_buscar1;
    private javax.swing.JTextField txt_buscar2;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_cedula1;
    private javax.swing.JTextField txt_cedula2;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_edad1;
    private javax.swing.JTextField txt_edad2;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id1;
    private javax.swing.JTextField txt_id2;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre1;
    private javax.swing.JTextField txt_nombre2;
    // End of variables declaration//GEN-END:variables
}
